"""Model backends for RAG retrieval value functions.

The demo keeps model loading behind a tiny interface so experiments can swap
from the local lexical scorer to Hugging Face models without changing the
shapiq game code.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property

import streamlit as st


@dataclass(frozen=True)
class GenerationResult:
    """Text generated by a model-backed RAG prompt."""

    answer: str


@st.cache_resource(show_spinner=False)
def cached_hf_tokenizer(model_id: str) -> object:
    """Load and cache one Hugging Face tokenizer."""
    try:
        from transformers import AutoTokenizer  # noqa: PLC0415
    except ImportError as error:  # pragma: no cover - depends on optional extra
        msg = (
            "Hugging Face scoring requires `transformers`. Install the demo "
            "requirements or the project's all_ml dependency group."
        )
        raise RuntimeError(msg) from error

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    if tokenizer.pad_token_id is None and tokenizer.eos_token_id is not None:
        tokenizer.pad_token = tokenizer.eos_token
    return tokenizer


@st.cache_resource(show_spinner=False)
def cached_hf_model(model_id: str, device_map: str, torch_dtype_name: str) -> object:
    """Load and cache one Hugging Face model."""
    try:
        import torch  # noqa: PLC0415
        from transformers import (  # noqa: PLC0415
            AutoConfig,
            AutoModelForCausalLM,
            AutoModelForImageTextToText,
        )
    except ImportError as error:  # pragma: no cover - depends on optional extra
        msg = (
            "Hugging Face scoring requires `torch` and `transformers`. Install "
            "the demo requirements or the project's all_ml dependency group."
        )
        raise RuntimeError(msg) from error

    torch_dtype = "auto" if torch_dtype_name == "auto" else getattr(torch, torch_dtype_name)
    model_kwargs = {
        "device_map": device_map,
        "torch_dtype": torch_dtype,
    }
    # Route to the correct Auto class by inspecting the model config, avoiding a
    # broad ValueError catch that would silently swallow unrelated config errors.
    config = AutoConfig.from_pretrained(model_id)
    architectures = getattr(config, "architectures", []) or []
    use_image_text = any(
        "ForConditionalGeneration" in arch or "ImageTextToText" in arch
        for arch in architectures
    )
    if use_image_text:
        model = AutoModelForImageTextToText.from_pretrained(model_id, **model_kwargs)
    else:
        model = AutoModelForCausalLM.from_pretrained(model_id, **model_kwargs)
    model.eval()
    return model


class HuggingFaceCausalLMBackend:
    """Small wrapper around a Hugging Face causal language model.

    The imports are intentionally lazy. This keeps the Streamlit demo usable in
    lightweight environments, while still making the final experiment path a
    direct Hugging Face model call.
    """

    def __init__(
        self,
        model_id: str,
        *,
        device_map: str = "auto",
        torch_dtype: str = "auto",
        max_new_tokens: int = 96,
    ) -> None:
        """Store Hugging Face loading and generation settings."""
        self.model_id = model_id
        self.device_map = device_map
        self.torch_dtype = torch_dtype
        self.max_new_tokens = max_new_tokens

    @cached_property
    def tokenizer(self) -> object:
        """Load the tokenizer on first use."""
        return cached_hf_tokenizer(self.model_id)

    @cached_property
    def model(self) -> object:
        """Load the causal language model on first use."""
        return cached_hf_model(self.model_id, self.device_map, self.torch_dtype)

    def build_chat_prompt(self, question: str, context: str) -> str:
        """Build a chat-style RAG prompt, using the tokenizer template if present."""
        messages = [
            {
                "role": "system",
                "content": (
                    "Answer the question using only the retrieved context. If the context "
                    "does not contain the answer, say that the provided context is insufficient. "
                    "For broad explanatory questions, synthesize all distinct evidence types in "
                    "the context instead of anchoring on the first or highest-scoring chunk. "
                    "Mention multiple scientific reasons when the context supports them, and "
                    "keep narrow subtopics as secondary points unless the question asks for them. "
                    "Be precise about location: "
                    "if the context discusses ejecta or materials from basins such as Orientale or "
                    "Tycho near a landing site, do not claim those basins are physically located at "
                    "the lunar south pole."
                ),
            },
            {
                "role": "user",
                "content": f"Question:\n{question}\n\nRetrieved context:\n{context}\n\nAnswer:",
            },
        ]
        if getattr(self.tokenizer, "chat_template", None):
            return self.tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        return (
            "Answer the question using only the retrieved context. If the context does not "
            "contain the answer, say that the provided context is insufficient. For broad "
            "explanatory questions, synthesize all distinct evidence types in the context instead "
            "of anchoring on the first or highest-scoring chunk. Mention multiple scientific "
            "reasons when supported, and keep narrow subtopics secondary unless asked. Be precise "
            "about location: ejecta or material near a site is not the same as the source basin "
            "being physically located there.\n\n"
            f"Question:\n{question}\n\n"
            f"Retrieved context:\n{context}\n\n"
            "Answer:"
        )

    def target_log_likelihood(self, prompt: str, target_answer: str) -> float:
        """Return average token log-likelihood of the target answer after the prompt."""
        import torch  # noqa: PLC0415

        if not target_answer.strip():
            return 0.0

        prompt_ids = self.tokenizer(prompt, return_tensors="pt").input_ids.to(self.model.device)
        target_ids = self.tokenizer(
            target_answer,
            add_special_tokens=False,
            return_tensors="pt",
        ).input_ids.to(self.model.device)
        input_ids = torch.cat([prompt_ids, target_ids], dim=1)

        with torch.no_grad():
            logits = self.model(input_ids=input_ids).logits

        target_start = prompt_ids.shape[1]
        token_logits = logits[:, target_start - 1 : -1, :]
        log_probs = torch.log_softmax(token_logits, dim=-1)
        selected = log_probs.gather(dim=-1, index=target_ids.unsqueeze(-1)).squeeze(-1)
        return float(selected.mean().detach().cpu())

    def generate(self, question: str, context: str) -> GenerationResult:
        """Generate an answer from the selected context."""
        import torch  # noqa: PLC0415

        prompt = self.build_chat_prompt(question, context)
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        pad_id = (
            getattr(self.tokenizer, "pad_token_id", None)
            or getattr(self.tokenizer, "eos_token_id", None)
            or 0
        )
        with torch.no_grad():
            output_ids = self.model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=False,
                pad_token_id=pad_id,
            )
        new_ids = output_ids[:, inputs.input_ids.shape[1] :]
        return GenerationResult(answer=self.tokenizer.decode(new_ids[0], skip_special_tokens=True))
