"""Local llama.cpp model backend for RAG generation and attribution scoring."""

from __future__ import annotations

import atexit
import math
import os
import re
import threading
from dataclasses import dataclass
from functools import cached_property, lru_cache
from pathlib import Path
from typing import Protocol

import numpy as np


class LlamaModel(Protocol):
    """Subset of the llama-cpp-python API used by this demo."""

    scores: np.ndarray

    def tokenize(
        self,
        text: bytes,
        *,
        add_bos: bool,
        special: bool,
    ) -> list[int]:
        """Tokenize input bytes."""

    def reset(self) -> None:
        """Reset the active llama.cpp context."""

    def eval(self, tokens: list[int]) -> None:
        """Evaluate tokens and retain logits."""

    def create_completion(self, **kwargs: object) -> dict[str, object]:
        """Generate one completion."""

    def close(self) -> None:
        """Release the llama.cpp context."""


@dataclass(frozen=True)
class GenerationResult:
    """Text generated by a model-backed RAG prompt."""

    answer: str


@lru_cache(maxsize=4)
def cached_llama_cpp_model(
    model_path: str,
    n_ctx: int,
    n_gpu_layers: int,
    n_threads: int,
) -> LlamaModel:
    """Load and cache one local GGUF model through llama.cpp."""
    path = Path(model_path).expanduser().resolve()
    if not path.is_file():
        msg = (
            f"GGUF model not found: {path}. Download a GGUF model and set its path "
            "on the Explanation Settings page."
        )
        raise RuntimeError(msg)
    try:
        from llama_cpp import Llama
    except ImportError as error:  # pragma: no cover - depends on optional dependency
        msg = (
            "Local model inference requires `llama-cpp-python`. Install the demo "
            "dependencies with `uv sync --group rag_demo`."
        )
        raise RuntimeError(msg) from error

    model = Llama(
        model_path=str(path),
        n_ctx=n_ctx,
        n_gpu_layers=n_gpu_layers,
        n_threads=n_threads,
        n_threads_batch=n_threads,
        logits_all=True,
        verbose=False,
    )
    atexit.register(model.close)
    return model


class LlamaCppBackend:
    """Run a local GGUF model for grounded generation and token likelihood."""

    def __init__(
        self,
        model_path: str,
        *,
        n_ctx: int = 4096,
        n_gpu_layers: int = -1,
        n_threads: int = 0,
        max_new_tokens: int = 96,
    ) -> None:
        """Store llama.cpp loading and generation settings."""
        self.model_path = str(Path(model_path).expanduser())
        self.n_ctx = n_ctx
        self.n_gpu_layers = n_gpu_layers
        self.n_threads = n_threads or max(1, (os.cpu_count() or 2) // 2)
        self.max_new_tokens = max_new_tokens
        self._lock = threading.RLock()

    @cached_property
    def model(self) -> LlamaModel:
        """Load the GGUF model on first use."""
        return cached_llama_cpp_model(
            self.model_path,
            self.n_ctx,
            self.n_gpu_layers,
            self.n_threads,
        )

    def build_prompt(self, question: str, context: str) -> str:
        """Build one deterministic grounded RAG completion prompt."""
        system_prompt = (
            "You are a grounded question-answering assistant.\n"
            "Use only the retrieved context below. If the context is insufficient, "
            "say so explicitly. Synthesize distinct evidence when the question is broad, "
            "and do not add unsupported claims."
        )
        user_prompt = f"Question:\n{question}\n\nRetrieved context:\n{context}"
        model_name = self.model_path.lower()
        if "qwen" in model_name:
            thinking_control = "\n/no_think" if "qwen3" in model_name else ""
            return (
                f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
                f"<|im_start|>user\n{user_prompt}{thinking_control}<|im_end|>\n"
                "<|im_start|>assistant\n"
            )
        if "gemma" in model_name:
            # Gemma 3 and Gemma 4 share the same chat template
            return (
                f"<start_of_turn>user\n{system_prompt}\n\n{user_prompt}<end_of_turn>\n"
                "<start_of_turn>model\n"
            )
        return f"{system_prompt}\n\n{user_prompt}\n\nAnswer:\n"

    def target_log_likelihood(self, prompt: str, target_answer: str) -> float:
        """Return average token log-likelihood of the target answer after the prompt."""
        if not target_answer.strip():
            return 0.0

        model = self.model
        prompt_tokens = model.tokenize(prompt.encode("utf-8"), add_bos=True, special=True)
        model_name = self.model_path.lower()
        answer_prefix = "<think>\n\n</think>\n\n" if "qwen3" in model_name else ""
        prefix_tokens = (
            model.tokenize(
                answer_prefix.encode("utf-8"),
                add_bos=False,
                special=True,
            )
            if answer_prefix
            else []
        )
        target_tokens = model.tokenize(
            target_answer.encode("utf-8"),
            add_bos=False,
            special=True,
        )
        full_tokens = [*prompt_tokens, *prefix_tokens, *target_tokens]
        if len(full_tokens) > self.n_ctx:
            msg = (
                f"Prompt and target require {len(full_tokens)} tokens, exceeding the "
                f"configured llama.cpp context size of {self.n_ctx}."
            )
            raise RuntimeError(msg)

        with self._lock:
            model.reset()
            model.eval(full_tokens)
            scores = np.asarray(model.scores)

        target_start = len(prompt_tokens) + len(prefix_tokens)
        token_logits = scores[target_start - 1 : len(full_tokens) - 1]
        if token_logits.shape[0] != len(target_tokens):
            msg = "llama.cpp did not return logits for every target token."
            raise RuntimeError(msg)

        selected_logits = token_logits[np.arange(len(target_tokens)), target_tokens]
        row_max = np.max(token_logits, axis=1)
        log_normalizers = row_max + np.log(
            np.exp(token_logits - row_max[:, np.newaxis]).sum(axis=1)
        )
        return float(np.mean(selected_logits - log_normalizers))

    def generate(self, question: str, context: str) -> GenerationResult:
        """Generate a deterministic answer from the selected context."""
        prompt = self.build_prompt(question, context)
        with self._lock:
            response = self.model.create_completion(
                prompt=prompt,
                max_tokens=self.max_new_tokens,
                temperature=0.0,
                top_p=1.0,
                repeat_penalty=1.05,
                stop=["<|im_end|>", "<end_of_turn>", "\n\nQuestion:", "\nRetrieved context:"],
            )
        choices = response.get("choices", [])
        answer = str(choices[0].get("text", "")) if choices else ""
        answer = re.sub(r"^\s*<think>.*?</think>\s*", "", answer, flags=re.DOTALL)
        return GenerationResult(answer=answer.strip())


def sigmoid(value: float) -> float:
    """Return a numerically stable logistic transform."""
    if value >= 0:
        return 1.0 / (1.0 + math.exp(-value))
    exp_value = math.exp(value)
    return exp_value / (1.0 + exp_value)
