import { useEffect, useRef } from "react";
import { ArrowUp, FlaskConical } from "lucide-react";
import type { ChatMessage } from "../types";
import { formatScore } from "../utils";

interface Props {
  messages: ChatMessage[];
  source: "sample" | "pdf";
  selectedScenario: { name: string; question: string; takeaway: string } | undefined;
  question: string;
  onQuestionChange: (q: string) => void;
  canRun: boolean;
  busy: boolean;
  error: string;
  onRun: () => void;
  onViewDetail: (id: string) => void;
}

export function ChatView({
  messages,
  source,
  selectedScenario,
  question,
  onQuestionChange,
  canRun,
  busy,
  error,
  onRun,
  onViewDetail,
}: Props) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, busy]);

  return (
    <div className="chat-layout">
      <div className="chat-messages">
        {messages.length === 0 && !busy && !error ? (
          <div className="empty-state">
            <div className="empty-rule" />
            <h2>Start an attribution run</h2>
            <p>
              {source === "sample"
                ? "Select a scenario on the left, then click Run attribution."
                : "Upload a PDF on the left, then type your question below."}
            </p>
          </div>
        ) : (
          messages.map((msg) => (
            <ChatTurn
              key={msg.id}
              message={msg}
              onViewDetail={() => onViewDetail(msg.id)}
            />
          ))
        )}

        {busy && (
          <div className="chat-thinking">
            <FlaskConical size={13} className="spin" />
            Computing attribution…
          </div>
        )}

        {error && <div className="error-box">{error}</div>}
        <div ref={bottomRef} />
      </div>

      <div className="chat-input-area">
        <div className="chat-input-inner">
          {source === "sample" ? (
            <div className="chat-sample-input">
              {selectedScenario ? (
                <span className="chat-sample-question">
                  {selectedScenario.question}
                </span>
              ) : (
                <span className="chat-no-scenario">No scenario selected</span>
              )}
              <button
                className="chat-run-btn"
                onClick={onRun}
                disabled={!canRun || busy}
              >
                {busy ? "Running…" : "Run attribution"}
              </button>
            </div>
          ) : (
            <div className="chat-free-input">
              <textarea
                value={question}
                onChange={(e) => onQuestionChange(e.target.value)}
                placeholder="Ask a question about the uploaded document…"
                rows={1}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    if (canRun && !busy) onRun();
                  }
                }}
              />
              <button
                className="chat-send-btn"
                onClick={onRun}
                disabled={!canRun || busy}
                aria-label="Run attribution"
              >
                <ArrowUp size={15} />
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function ChatTurn({
  message,
  onViewDetail,
}: {
  message: ChatMessage;
  onViewDetail: () => void;
}) {
  const active = message.result.results[message.resultIndex];
  const answerLabel =
    message.result.answer_target_type === "generated_answer"
      ? "Generated answer"
      : "Reference answer";

  return (
    <div className="chat-turn">
      <div className="chat-question">
        <span className="chat-q-label">Q</span>
        <p className="chat-q-text">{message.question}</p>
      </div>

      <div className="chat-answer">
        {message.modelDisplayName && (
          <p className="chat-model-byline">
            Generated by {message.modelDisplayName}
          </p>
        )}
        <span className="chat-target-label">{answerLabel}</span>
        <p className="chat-answer-text">{message.result.answer}</p>
        {active && (
          <div className="chat-answer-meta">
            <span>Evidence support: {formatScore(active.full_score, false)}</span>
            <span>·</span>
            <span>{message.result.chunks.length} chunks</span>
            <span>·</span>
            <span>{active.value_name}</span>
            {message.interactionIndex && (
              <>
                <span>·</span>
                <span>{message.interactionIndex}</span>
              </>
            )}
          </div>
        )}
        <button className="chat-detail-btn" onClick={onViewDetail}>
          View evidence details →
        </button>
      </div>
    </div>
  );
}
